#!/bin/bash

##############################################################################
#
# remove_old_data - removes files older than [configurable] number of days
#
# remove_old_data [/path/to/target/dir] [file_ext] [int_days] [int_KB]
#
# EXAMPLE USAGE:
#  $ remove_old_data /path/to/dir '.psv' 3 2048
#
# ENV OPTIONS:
#  VERBOSE - default is unset, any nonzero value sets verbose output, e.g:
#    $ VERBOSE=1 remove_old_data /path/to/dir '.psv' 3 2048
#
# TODO:
#   This program utilizes filesystem mtime.  Fielsystem mtime/atime is not
#   always to be trusted as correct, (creation time is trustworthy).
#
# cgutierrez@
#
##############################################################################

yell() { echo "$0: $*" >&2; }
die() { yell "$*"; exit 111; }
try() { "$@" || die "cannot $*"; }

data_dir="$1"
fext="$2"
cutoff_days="$3"
if [ $cutoff_days -eq "0" ]; then
  cutoff_days="-1"
fi
#: ${data_dir:="/mnt/DS/tmp"}
max_dir_size="$4"

size="`try du -ks $data_dir | awk '{print $1}'`"

if [ "$size" -gt $4 ]; then

  if [ -n "$VERBOSE" ] ; then
    yell "----------------------------------------------"
    yell "Data directory : "$data_dir
    yell "Removing files with extension : "$fext
    yell "Cut-off days back : "$cutoff_days
    yell "Max. directory size (in KB) : "$max_dir_size
    yell "----------------------------------------------"
  fi

  [ -n "$VERBOSE" ] && yell "Current directory size (in KB) : $size"

  file_list=(`find $data_dir -type f -name "*$fext" -mtime +"$cutoff_days"`);   

  if [ ${#file_list[@]} -gt 0 ]; then
       
    if [ -n "$VERBOSE" ]; then 
	    if [ ${#file_list[@]} -le 5 ]; then
        ( IFS=$'\n'; yell "Files of type $fext older than $cutoff_days days: "$'\n'${file_list[@]} )
      else
        ( IFS=$'\n'; yell "Files of type $fext older than $cutoff_days days: "$'\n'${file_list[@]:0:5}" ... [${#file_list[@]} total]" )
      fi
      read -p "Do you want to delete all these files? " -n 1 -r
	
	    if [[ $REPLY =~ ^[Yy]$ ]]; then
        yell ">>>"
        yell "Deleting files more than $cutoff_days days old."
        try find "$data_dir" -type f -name "*$fext" -mtime +"$cutoff_days" -print0 | xargs -0 rm -v # --verbose # option not available to MacOSX xargs
      fi

    else
	    try find "$data_dir" -type f -name "*$fext" -mtime +"$cutoff_days" -print0 | xargs -0 rm
    fi
  
  else
	  [ -n "$VERBOSE" ] && yell "No files of type $fext more than $cutoff_days days old."
  fi

else
  [ -n "$VERBOSE" ] && yell "There is space available in $data_dir >>> No files deleted."
fi


true
